local p = {}

p["farm - level 1"] = {
	dif = "dif_easy",
	{type = "PlaceUnit", unit = "unit_cactus", id = 3, position = Vector3.new(-332.280, 61.680, -134.541), rotation = -180},
	{type = "PlaceUnit", unit = "unit_cactus", id = 4, position = Vector3.new(-332.312, 61.680, -132.878), rotation = -180},
	{type = "PlaceUnit", unit = "unit_palm_tree", id = 11, position = Vector3.new(-326.046, 61.680, -128.048), rotation = -180},
	{type = "PlaceUnit", unit = "unit_cactus", id = 18, position = Vector3.new(-332.369, 61.680, -131.291), rotation = -180},
	{type = "PlaceUnit", unit = "unit_flame_leaf", id = 30, position = Vector3.new(-324.627, 61.680, -124.958), rotation = -180},
	{type = "UpgradeUnit", unit = "unit_flame_leaf", id = 30, level = 2},
	{type = "UpgradeUnit", unit = "unit_flame_leaf", id = 30, level = 3},
	{type = "PlaceUnit", unit = "unit_flame_leaf", id = 42, position = Vector3.new(-327.966, 61.680, -98.302), rotation = -180},
	{type = "PlaceUnit", unit = "unit_flame_leaf", id = 48, position = Vector3.new(-327.803, 61.680, -102.565), rotation = -180},
	{type = "PlaceUnit", unit = "unit_flame_leaf", id = 49, position = Vector3.new(-327.233, 61.680, -108.134), rotation = -180},
	{type = "UpgradeUnit", unit = "unit_flame_leaf", id = 42, level = 2},
	{type = "UpgradeUnit", unit = "unit_flame_leaf", id = 48, level = 2},
	{type = "UpgradeUnit", unit = "unit_flame_leaf", id = 49, level = 2},
	{type = "UpgradeUnit", unit = "unit_flame_leaf", id = 42, level = 3},
	{type = "UpgradeUnit", unit = "unit_flame_leaf", id = 48, level = 3},
	{type = "UpgradeUnit", unit = "unit_flame_leaf", id = 49, level = 3},
	{type = "UpgradeUnit", unit = "unit_palm_tree", id = 11, level = 2},
	{type = "UpgradeUnit", unit = "unit_cactus", id = 18, level = 2},
	{type = "UpgradeUnit", unit = "unit_cactus", id = 4, level = 2},
	{type = "UpgradeUnit", unit = "unit_cactus", id = 3, level = 2},
	{type = "UpgradeUnit", unit = "unit_cactus", id = 3, level = 3},
	{type = "UpgradeUnit", unit = "unit_cactus", id = 4, level = 3},
	{type = "UpgradeUnit", unit = "unit_cactus", id = 18, level = 3},
	{type = "UpgradeUnit", unit = "unit_cactus", id = 3, level = 4},
	{type = "UpgradeUnit", unit = "unit_cactus", id = 4, level = 4},
	{type = "UpgradeUnit", unit = "unit_cactus", id = 18, level = 4},
}

return p